// <auto-generated />
namespace IC.LMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CompanyInfoNewChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CompanyInfoNewChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201612160942447_CompanyInfoNewChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
