// <auto-generated />
namespace IC.LMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ElmahMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ElmahMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201612151016408_ElmahMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
